

name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual workflow runs
  workflow_dispatch:
  # Update on push to main branch
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token (required)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: mandar00
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Languages plugin configuration
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 15
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: bytes-size, percentage

          
          # Additional plugins (optional - you can enable more)
          plugin_followup: yes
          plugin_followup_sections: repositories
          
          plugin_gists: yes
          
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_lines: yes
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          
          plugin_people: yes
          plugin_people_types: followers, following
          
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          
          plugin_stars: yes
          plugin_stars_limit: 4